# Generated by Django 6.0.5 on 2026-05-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=17)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('ficcao', 'Ficção'), ('nao_ficcao', 'Não-ficção'), ('romance', 'Romance'), ('aventura', 'Aventura'), ('ciencia', 'Ciência'), ('historia', 'História'), ('infantil', 'Infantil'), ('outros', 'Outros')], max_length=20)),
                ('quantidade', models.IntegerField(default=1)),
                ('sinopse', models.TextField(blank=True)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
